# Generated by Django 3.1 on 2020-08-22 08:35

import community.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('intro_paragraph', models.TextField()),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('author', models.ForeignKey(on_delete=models.SET(community.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
